#!/bin/bash
. build/common/functions

target=$(handleArgs --target $*)
file=$(handleArgs --file $*)
projectName=`echo $file | sed "s/.ipa//"`
projectId=$(getProjectIdFromFile $file)
link=$(getDropboxUrl $target $file)
version=`node -pe "require('./package.json').version"`
plist="build/common/publish/dropbox/"$projectName".plist"
rm -rf $plist

echo "<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>items</key>
        <array>
            <dict>
                <key>assets</key>
                <array>
                    <dict>
                        <key>kind</key>
                        <string>software-package</string>
                        <key>url</key>
                        <string>$link</string>
                    </dict>
                </array>
                <key>metadata</key>
                <dict>
                    <key>bundle-identifier</key>
                    <string>$projectId</string>
                    <key>bundle-version</key>
                    <string>$version</string>
                    <key>kind</key>
                    <string>software</string>
                    <key>title</key>
                    <string>$projectName</string>
                </dict>
            </dict>
        </array>
    </dict>
</plist>" >> $plist

build/common/publish/dropbox/dropbox_uploader.sh upload $plist $target

rm -rf $plist
