#!/bin/bash

all_stands=("shell" "qatar" "test01" "online")
confluence_page_develop=179863673
confluence_page_other=182911005
defaultOutputPath=build/outputs/
archivePath=$HOME/Documents/RSHB_MBUL/archive/rshb_mbul
dropboxPath=Jenkins/RSHB_MBUL
archivePathMarket=$archivePath"_market"
dropboxPathMarket=$dropboxPath"/market"

exportOptions=common/ios/ExportOptions.plist

projectName=UL
projectId=ru.softlab.rshb.mbul
versionName=""
url_shell=http://localhost:8081/ib6/rest
url_qatar=http://localhost:8080/ib6/rest
url_test01=https://test/ib6/rest
url_online=https://online/ib6/rest
enableSSLPinning_shell=false
enableSSLPinning_qatar=false
enableSSLPinning_test01=true
enableSSLPinning_online=true

projectName_market=РСХБизнес
projectId_market_ios=ru.softlab.mbul1
projectId_market_android=ru.softlab.mbul
url_market=https://online/ib6/rest
version_market_ios=1.1.5
version_market_android=1.1.3
